### ISSUE TITLE
Add content from Sheldon et al. (2020)

### ISSUE THREAD

**Issue by sfarrens** [CosmoStat/Shear-and-PSF-Reading-Group#18]
- [ ] New page describing metadetection

**Comment by thuiop** [comment]
As we said earlier today I am taking over this issue ; I mostly have one question before I start working on it : where do we want the content to go ? I can see this going next to metacalibration, so should it be in the shear calibration section ? Or another one since metadetection is also related to detection obviously ? (in the worst case we can move the page around if needed though)

**Comment by thuiop** [comment]
Should be closed now I guess
