### ISSUE TITLE
Finalise content from Kacprzak et al. (2014)

### ISSUE THREAD

**Issue by sfarrens** [CosmoStat/Shear-and-PSF-Reading-Group#5]
Decide on what content from Kacprzak et al. (2014) should be included and how.

- [x] Do literature review to see if there are any other references to model + noise bias interaction

**Comment by sfarrens** [comment]
Separate section for bias and bias calibration

**Comment by fadinammour** [comment]
Suggestion: put Interaction Between Model and Noise Biases part in a subsection rather than a section.
Motive: the effect of the interaction effect seems to be minor, we have only seen it mentioned in Kacprzak et al (2014) so far and it is a bit hard to grasp as a concept for beginner that is reading the book.

**Comment by sfarrens** [comment]
@fadinammour I have followed your advice and updated PR #4 accordingly.
